title:             Statix Hotel Jekyll Theme
description:       A Hotel Theme by Statix Design
email:             your-email@example.com
author:            Statix Design
baseurl:           "/statix-hotel-jekyll"
url:               "http://statixdesign.github.io"

# Social Profiles
twitter_username:  statixdesign
github_username:   statixdesign
facebook_username: statixdesign

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-tidy


